### ISSUE TITLE
vtecxblankのチュートリアル作成

### ISSUE THREAD

**Issue by takeyama** [reflexworks/vtecxblank#100]
HelloWorld的なものと、メニューがあるもの（登録、一覧、ページネーション）

**Comment by takeyama** [comment]
暫定版のデモ画面を作成しました。
typescriptprojブランチにpush済みなので、チェックアウトして確認お願いします。
demo.htmlです。

**Comment by takezaki** [comment]
チェックアウトして一通り試してみました。
とてもわかりやすいと思います。

また、ソースも確認しました。anyが多かったので入れられる型を追加しています。
更新して、npm installしてください。

https://github.com/reflexworks/vtecxblank/commit/84d796ec3df7e46c7178216fe7e59d4a7afd297e

**Comment by takezaki** [comment]
一点、PUTの際にid指定を省略することができることは説明した方がいいと思います。
省略した場合は、強制上書きになります。
また、DELETEの際にも、リビジョンを省略できます。

**Comment by takezaki** [comment]
また、応用編になるのかもしれませんが、25件以上の登録や更新はput bulkを使う必要があり、そういう意味で、putを標準的に使うべきで、postは非推奨にすべきかと思います。

**Comment by takeyama** [comment]
更新削除でリビジョン省略と25件以上の登録更新は応用編で行います。
