### ISSUE TITLE
react-password-strengthのTypeScriptバージョン

### ISSUE THREAD

**Issue by takeyama** [reflexworks/vtecxblank#102]
react-password-strengthがtsエラーとなります。
`npm install @types/react-password-strength`が存在しないため、別のコンポーネントを準備する必要があります。

**Comment by takezaki** [comment]
別のコンポーネントにしたくないので、なんとか回避する方法が見つかるといいのですが。

**Comment by takeyama** [comment]
やってみます。

**Comment by takeyama** [comment]
react-password-strengthのtypescript化をやりました。
しかし、change_password.tsxにimportしようとすると以下のエラーとなります。
原因はなんでしょうか？
```
ERROR in ./src/components/change_password.tsx
Module not found: Error: Can't resolve './password_strength' in '/Users/takeyama/git/vtecxblank/src/components'
 @ ./src/components/change_password.tsx 20:26-56
```

最新のソースをチェックアウトすると現象が発生すると思います。

**Comment by takezaki** [comment]
gulpファイルを修正しました。
zxcvbnがインストールされてなかったのでpackage.jsonに追加しました。
チェックアウトして、npm installしてください。

**Comment by takeyama** [comment]
確認しました。
クローズします。
