### ISSUE TITLE
vtecxadminの対応で変更したgulpファイルをvtecxblankに適用する

### ISSUE THREAD

**Issue by takeyama** [reflexworks/vtecxblank#103]
vtecxadminの対応で変更したgulpファイルがvtecxblankに適用されていないようです。

**Comment by takezaki** [comment]
具体的にどの部分ですか？

**Comment by takeyama** [comment]
画像の形式はできていないように見えます。
漏れがないようにvtecadminから差分を取ってこちらに更新お願いします。

**Comment by takeyama** [comment]
すみません。svgの形式はありました。
もう一度確認してからコメントします。

**Comment by takeyama** [comment]
最新になっていたのでクローズ
