### ISSUE TITLE
ユーザ登録メールが送信できない

### ISSUE THREAD

**Issue by takeyama** [reflexworks/vtecxblank#104]
現状のvtecxblankのソースをデプロイし、ユーザ登録しようとすると以下のエラーになり送信できません。
```
feed: {title: "Mail setting is required : _mail.from"}
```

vtecadminではユーザ登録できます。
違いはadduserinfo.xmlのsummaryが空なくらいなのですが、何が原因でしょうか？

**Comment by takeyama** [comment]
ちなみに/_settings/adduserが登録できていることは確認済みです。

**Comment by takezaki** [comment]
メール設定はサービスごとに設定するようになりました。
このチケットはpublicなので設定情報を記載できません。
vtecxadminのチケットに記入します。

**Comment by takeyama** [comment]
vtecxadminの管理画面で設定できるようにする。

**Comment by takeyama** [comment]
管理画面で設定できるようになったのでクローズ
