### ISSUE TITLE
folderacls.xmlの中身が空の場合、デプロイに失敗する

### ISSUE THREAD

**Issue by takeyama** [reflexworks/vtecxblank#105]
folderacls.xmlはユーザ独自のエンドポイント情報が格納されますが、初期状態は中身は空を想定しています。
folderacls.xmlファイル自体はエンドポイント情報を格納する受け皿として、中身が空でも必要なため、gulpファイルで中身が空の場合は処理を飛ばす対応をしてもらいたいです。

**Comment by takezaki** [comment]
修正しました

**Comment by takeyama** [comment]
確認しました。
