### ISSUE TITLE
vtecxblankのTypeScript化

### ISSUE THREAD

**Issue by takeyama** [reflexworks/vtecxblank#99]
TypeScriptに対応したblankプロジェクトを作成しました。以下からチェックアウトしてください。
https://github.com/reflexworks/vtecxblank/tree/typescriptproj

今のところ動くのは以下の２つだけです。

 * フロントエンド
   * src/components/index.tsx
 * サーバサイドスクリプト(http://vtecxblank.vte.cx/s/ssr.html)
   * server/ssr.html.tsx

TypeScriptでは、拡張子が.tsx(JSXを使う場合）と.ts(JSXを使わない場合）になります。
基本的に型が強要されるので注意してください。使い方はこれを参照してください。
http://js.studio-kingdom.com/typescript/

**Comment by takeyama** [comment]
TypeScript化しました。
確認お願いします。

**Comment by takezaki** [comment]
確認しました
